# Generated by Django 2.2.12 on 2021-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210607_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
