# Generated by Django 2.2.12 on 2021-06-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210607_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='imię_i_nazwisko',
        ),
    ]
