# Generated by Django 2.2.12 on 2021-06-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210607_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='adres',
        ),
    ]
