# Generated by Django 2.2.12 on 2021-06-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210607_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_by',
            new_name='zamówiony_przez',
        ),
    ]
