# Generated by Django 2.2.12 on 2021-06-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210608_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='imię_i_nazwisko',
            new_name='zamówiony_przez',
        ),
    ]
