# Generated by Django 2.2.12 on 2021-06-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210608_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_by',
            new_name='zamówiony_przez',
        ),
    ]
