# Generated by Django 2.2.12 on 2021-06-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210608_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='adres_wysyłki',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='metoda_płatności',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='telefon',
        ),
    ]
