# Generated by Django 2.2.12 on 2021-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210608_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
